### ISSUE TITLE
TypeError: this.client.utils.removeDuplicates is not a function

### ISSUE THREAD

**Issue by Lemorz56** [MenuDocs/discord.js-template#6]
So when running the help command i get,

`
(node:347) UnhandledPromiseRejectionWarning: TypeError: this.client.utils.removeDuplicates is not a function
    at module.exports.run (/src/Commands/Help.js:45:36)
    at module.exports.run (/src/Events/message/message.js:20:12)
    at MenuDocsClient.<anonymous> (/src/Structures/Util.js:52:56)
    at MenuDocsClient.emit (events.js:315:20)
    at MessageCreateAction.handle (/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/node_modules/ws/lib/event-target.js:132:16)
`

**Comment by birongliu** [comment]
Probably should join Menudocs server and ask for help in discordjs channel.
